In [4]:

np.ones((5,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [94]:
print("hey there i am vasim")

hey there i am vasim


In [95]:
import numpy as np

np.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
import numpy as np 
list=[5,1,2,5,2,5,5]
arr=np.array(list)
arr

array([5, 1, 2, 5, 2, 5, 5])

In [96]:

np.random.randint(1,100,(3,3))

array([[32, 24, 33],
       [63, 11, 16],
       [69, 40, 38]])

In [97]:

np.random.seed(44)
np.random.randint(1,100,(3,3))

array([[21, 36, 46],
       [60,  4, 97],
       [85,  4, 24]])

In [99]:
np.random.seed(15)
arr=np.random.randint(1,200,10)
arr


array([141, 134, 120, 129, 157, 156,  86, 119, 176,  18])

In [8]:
import numpy as np
np.random.seed(15)
arr=np.random.randint(1,200,10)
arr

arr.max()
arr.min()
arr.sum()
arr.mean()

arr.argmax()
arr.argmin()
arr.reshape(5,2)
 

array([[141, 134],
       [120, 129],
       [157, 156],
       [ 86, 119],
       [176,  18]])

In [12]:
mat= np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [15]:
mat[2,3]

23

In [19]:
mat[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [24]:
mat[0,:]


array([0, 1, 2, 3, 4, 5])

In [22]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])